using Ecommerce.Common.Interfaces;
using System.Text.Json.Serialization;

namespace Ecommerce.Common.Models.Schema
{
    /// <summary>
    /// Category model.
    /// </summary>
    public class Category : IEntity
    {
        /// <summary>
        /// Category ID.
        /// </summary>
        /// <remarks>An unique identifier generated by the system.</remarks>
        /// <example>73190</example>
        public int Id { get; set; }

        /// <summary>
        /// ID of the parent category, if any.
        /// </summary>
        /// <example>291</example>
        public int? ParentId { get; set; }

        /// <summary>
        /// Category name.
        /// </summary>
        /// <example>Beverages</example>
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Category description.
        /// </summary>
        /// <example>Drinks and beverages.</example>
        public string Description { get; set; } = string.Empty;

        /// <summary>
        /// Thumbnail ID.
        /// </summary>
        [JsonIgnore]
        public int? ThumbnailId { get; set; }

        /// <summary>
        /// Thumbnail.
        /// </summary>
        public virtual MediaImage? Thumbnail { get; set; }
        
        /// <summary>
        /// Subcategories.
        /// </summary>
        public virtual ICollection<Category> Subcategories { get; set; } = new List<Category>();

        /// <summary>
        /// List of products assigned to the category.
        /// </summary>
        [JsonIgnore]
        public virtual ICollection<Product> Products { get; set; } = new List<Product>();

        /// <summary>
        /// Whether the category is enabled or not.
        /// </summary>
        public bool Enabled { get; set; }

        /// <summary>
        /// Datetime of creation.
        /// </summary>
        public DateTime CreatedAt { get; set; }
        
        /// <summary>
        /// Datetime of last modification.
        /// </summary>
        public DateTime UpdatedAt { get; set; }
    }
}
