using Ecommerce.Common.Interfaces;
using System.Text.Json.Serialization;

namespace Ecommerce.Common.Models.Schema
{
    /// <summary>
    /// Product model.
    /// </summary>
    public class Product : IEntity
    {
        /// <summary>
        /// Product ID.
        /// </summary>
        /// <remarks>An unique identifier generated by the system.</remarks>
        /// <example>1037801</example>
        public int Id { get; set; }
        
        /// <summary>
        /// Product SKU.
        /// </summary>
        /// <remarks>An unique identifier provided by the user.</remarks>
        /// <example>BEVERAGE0001</example>
        public string Sku { get; set; } = string.Empty;
        
        /// <summary>
        /// Product name.
        /// </summary>
        /// <example>Orange juice</example>
        public string Name { get; set; } = string.Empty;
        
        /// <summary>
        /// Product description.
        /// </summary>
        /// <example>A 600ml bottle of juice with orange flavor.</example>
        public string Description { get; set; } = string.Empty;
        
        /// <summary>
        /// Product price.
        /// </summary>
        /// <example>8.00</example>
        public decimal Price { get; set; }

        /// <summary>
        /// Formatted price.
        /// </summary>
        /// <example>$8.00</example>
        public string FormattedPrice => $"{Price:C}";
        
        /// <summary>
        /// If not null, display a price to compare to.
        /// </summary>
        /// <remarks>
        /// When a discount is available, Price displays the price with discount
        /// while CrossedOutPrice displays the original price.
        /// </remarks>
        /// <example>9.99</example>
        public decimal? CrossedOutPrice { get; set; }

        /// <summary>
        /// Formatted crossed out price.
        /// </summary>
        /// <example>$9.99</example>
        public string? FormattedCrossedOutPrice => (CrossedOutPrice != null) ? $"{CrossedOutPrice:C}" : null;

        /// <summary>
        /// Thumbnail ID.
        /// </summary>
        [JsonIgnore]
        public int? ThumbnailId { get; set; }
        
        /// <summary>
        /// Thumbnail.
        /// </summary>
        public virtual MediaImage? Thumbnail { get; set; }
        
        /// <summary>
        /// Gallery images.
        /// </summary>
        public virtual ICollection<MediaImage> GalleryImages { get; set; } = new List<MediaImage>();

        /// <summary>
        /// ID of the categories the product is assigned to.
        /// </summary>
        public virtual ICollection<int> CategoryIds => Categories.Select(x => x.Id).ToList();

        /// <summary>
        /// List of categories the product is assigned to.
        /// </summary>
        [JsonIgnore]
        public virtual ICollection<Category> Categories { get; set; } = new List<Category>();

        /// <summary>
        /// Product attributes.
        /// </summary>
        public virtual ICollection<ProductAttribute> Attributes { get; set; } = new List<ProductAttribute>();

        /// <summary>
        /// Product width.
        /// </summary>
        public double? Width { get; set; }

        /// <summary>
        /// Formated width.
        /// </summary>
        public string? FormattedWidth => (Width != null && DimensionUnits != null) ? $"{Width} {DimensionUnits}".ToLower() : null;

        /// <summary>
        /// Product height.
        /// </summary>
        public double? Height { get; set; }

        /// <summary>
        /// Formatted height.
        /// </summary>
        public string? FormattedHeight => (Height != null && DimensionUnits != null) ? $"{Height} {DimensionUnits}".ToLower() : null;

        /// <summary>
        /// Product length.
        /// </summary>
        public double? Length { get; set; }

        /// <summary>
        /// Formatted length.
        /// </summary>
        public string? FormattedLength => (Length != null && DimensionUnits != null) ? $"{Length} {DimensionUnits}".ToLower() : null;

        /// <summary>
        /// Dimension units.
        /// </summary>
        public DimensionUnits? DimensionUnits { get; set; }
        
        /// <summary>
        /// Product weight.
        /// </summary>
        public double? Weight { get; set; }

        /// <summary>
        /// Formatted weight.
        /// </summary>
        public string? FormattedWeight => (Weight != null && WeightUnits != null) ? $"{Weight} {WeightUnits}".ToLower() : null;

        /// <summary>
        /// Weight units.
        /// </summary>
        public WeightUnits? WeightUnits { get; set; }

        /// <summary>
        /// Minimum allowed purchase quantity.
        /// </summary>
        /// <example>1</example>
        public int MinPurchaseQuantity { get; set; }

        /// <summary>
        /// Maximum allowed purchase quantity.
        /// </summary>
        /// <example>10</example>
        public int MaxPurchaseQuantity { get; set; }
        
        /// <summary>
        /// Available number of products in stock, or null if unlimited.
        /// </summary>
        /// <example>300</example>
        public int? InStock { get; set; }

        /// <summary>
        /// Whether the product is enabled or not.
        /// </summary>
        public bool Enabled { get; set; }

        /// <summary>
        /// Datetime of creation.
        /// </summary>
        public DateTime CreatedAt { get; set; }
        
        /// <summary>
        /// Datetime of last modification.
        /// </summary>
        public DateTime UpdatedAt { get; set; }
    }
}
